// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vypjeqzatumvciiwdmga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5cGplcXphdHVtdmNpaXdkbWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNTkzNDksImV4cCI6MjA1MzgzNTM0OX0.GTCY8MYRcgA8R_UCOI-wCgIbNJSqNUd_VZBDIyvYVpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);